-- ============================================================================
-- MemberJunction PostgreSQL Migration — V202606171200__skip_client_security_seed.sql
-- Generated by the split-and-regenerate pipeline (AST dialect transpile of
-- hand-written DDL; CodeGen objects regenerated natively; metadata re-seeded).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;
SET standard_conforming_strings = on;

BEGIN;
/* ── Skip Service role ─────────────────────────────────────────────────────── */;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "${mjSchema}"."Role" WHERE "ID" = '9933BBB6-4139-4256-8087-64F4B9E4351F') THEN
    INSERT INTO "${mjSchema}"."Role" ("ID", "Name", "Description") VALUES ('9933BBB6-4139-4256-8087-64F4B9E4351F', 'Skip Service', 'Role for the Skip Service Account. Grants CRUD on query-related entities needed for Skip callback operations (query creation, update, deletion). Pair with the UI role for broad read access.');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "${mjSchema}"."User" WHERE "ID" = '0199FC9E-1468-57FC-8A4E-EF1131DA76EB') THEN
    INSERT INTO "${mjSchema}"."User" ("ID", "Name", "FirstName", "LastName", "Email", "Type", "IsActive", "LinkedRecordType") VALUES ('0199FC9E-1468-57FC-8A4E-EF1131DA76EB', 'Skip Service Account', 'Skip', 'Service', 'skip-service@skip.internal', 'User', TRUE, 'None');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "${mjSchema}"."UserRole" WHERE "ID" = '65BC9077-D7B9-49BE-B610-90CA037217DC') THEN
    INSERT INTO "${mjSchema}"."UserRole" ("ID", "UserID", "RoleID") VALUES ('65BC9077-D7B9-49BE-B610-90CA037217DC', '0199FC9E-1468-57FC-8A4E-EF1131DA76EB', (SELECT "ID" FROM "${mjSchema}"."Role" WHERE "Name" = 'UI'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "${mjSchema}"."UserRole" WHERE "ID" = '60022E69-E534-4AE6-B399-814B36F721A3') THEN
    INSERT INTO "${mjSchema}"."UserRole" ("ID", "UserID", "RoleID") VALUES ('60022E69-E534-4AE6-B399-814B36F721A3', '0199FC9E-1468-57FC-8A4E-EF1131DA76EB', '9933BBB6-4139-4256-8087-64F4B9E4351F');
  END IF;
END $$;

/* ── Entity permissions: full CRUD for Skip Service on the MJ Query* family ─── */;
-- Hand-ported (AST transpiler gap — top-level DECLARE + WITH-driven INSERT are
-- outside its supported grammar; reported in conversion-gaps.report.json, not
-- silently dropped). Same DO $$ idiom + quoting the transpiler used above.
DO $$
DECLARE
  v_SkipServiceRoleID UUID := '9933BBB6-4139-4256-8087-64F4B9E4351F';
BEGIN
  WITH "SkipPerms" ("ID", "EntityName") AS (
    SELECT 'B7C1A009-197B-4987-9C45-11AE070AE02F', 'MJ: Queries'            UNION ALL
    SELECT '14E94742-B25D-478A-9409-394E658B32A7', 'MJ: Query Categories'   UNION ALL
    SELECT 'F1BD10D7-86C7-43BD-A8E0-75B77C2BA503', 'MJ: Query Fields'       UNION ALL
    SELECT '7E6AD1F0-1DAB-4441-923C-338997702ABC', 'MJ: Query Parameters'   UNION ALL
    SELECT '52D4A00C-AE6A-4C73-B4B0-C40D922054EE', 'MJ: Query Entities'     UNION ALL
    SELECT '22A6A4DC-39DF-4E3D-AC46-CAB491F7B308', 'MJ: Query Permissions'  UNION ALL
    SELECT '21E86DC8-3E03-41DC-B8E6-B36324666C21', 'MJ: Query Dependencies' UNION ALL
    SELECT '14BA1F89-0FB7-43E9-A283-2EB9A9FF4BBF', 'MJ: Query SQLs'
  )
  INSERT INTO "${mjSchema}"."EntityPermission" ("ID", "EntityID", "RoleID", "CanCreate", "CanRead", "CanUpdate", "CanDelete", "Type")
  SELECT p."ID"::UUID, e."ID", v_SkipServiceRoleID, TRUE, TRUE, TRUE, TRUE, 'Allow'
  FROM "SkipPerms" p
  INNER JOIN "${mjSchema}"."Entity" e ON e."Name" = p."EntityName"
  WHERE NOT EXISTS (SELECT 1 FROM "${mjSchema}"."EntityPermission" ep WHERE ep."ID" = p."ID"::UUID);
END $$;

COMMIT;
